import React from 'react'

export const About = () => (
  <div>
    <h2>About Page</h2>
    <p>This is mostly about us.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget posuere eros, nec lobortis eros. Aenean porttitor efficitur ligula. Nulla sodales arcu augue, at interdum velit fringilla a. Donec urna mauris, interdum ac porta sit amet, elementum id tellus. Integer dapibus volutpat consectetur. Quisque nec fermentum velit. Cras ut imperdiet odio, id semper nisl.</p>
    <p>Sed egestas ligula ac nibh interdum, eget laoreet massa dapibus. Duis placerat eros magna, ac viverra orci volutpat ac. Sed eget arcu non dui placerat gravida vel lacinia quam. Aenean tincidunt neque quis leo feugiat feugiat. Nulla leo nulla, ullamcorper eu iaculis sed, semper a dui. Aenean eu ultricies lorem, eget consectetur metus. Nullam venenatis pharetra velit, vitae feugiat risus. Pellentesque faucibus vulputate mi, id eleifend eros tincidunt vestibulum. Mauris placerat ullamcorper ante. Sed porta sodales metus et condimentum. Aenean placerat nibh eu laoreet tempor. Etiam vel pellentesque nisi. Maecenas in sapien enim. Nam a consectetur lorem.Sed iaculis, quam eget viverra volutpat, diam ex suscipit ligula, ac porta sapien ex et nibh. Duis vehicula non augue eget elementum. Donec eget ullamcorper lorem. Sed ut ligula vitae est hendrerit tincidunt. Morbi luctus diam sed nisi aliquam varius. Sed dictum lorem dolor, at gravida diam ultrices id. Proin ac mauris condimentum nisi auctor fermentum ut a nibh. Sed semper pellentesque volutpat.</p>
    <p>Nam viverra nulla sed malesuada lacinia. Cras ut massa eu lorem consequat lobortis. Cras libero nulla, facilisis eu ligula non, lobortis cursus orci. Nam vehicula, neque ut tempus vehicula, est leo pulvinar enim, vitae porta tortor neque eu mauris. Aliquam pulvinar enim ut faucibus viverra. Nulla convallis efficitur eros, non luctus neque fringilla ac. Nam blandit accumsan semper. Aliquam erat volutpat. Fusce sagittis diam non nisi fermentum, eu malesuada dui rhoncus. Nulla pharetra dolor vitae euismod tristique. Donec eget congue quam. Phasellus sit amet molestie nunc, ut pulvinar est.Pellentesque nec tincidunt nulla. Nunc vehicula eget felis vitae tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam suscipit eget nulla sed tincidunt. Phasellus tristique purus sed ipsum mattis mollis et at arcu. Etiam tellus nibh, posuere malesuada lacus at, elementum consectetur lectus. Maecenas vestibulum, ligula eu congue ultrices, leo turpis varius libero, vitae dictum erat purus at leo. Pellentesque quis nunc non eros auctor elementum a a dui. Vivamus pretium nulla ipsum, eu hendrerit odio vehicula varius. Phasellus sed nunc sit amet lorem molestie varius at a justo. Vivamus in orci et risus viverra porta a a mi.</p>
    <p>Nulla lorem odio, efficitur vel semper nec, eleifend in ante. Fusce sodales elementum mi nec iaculis. Praesent efficitur commodo scelerisque. Aliquam tempor laoreet blandit. Morbi non facilisis ipsum, dapibus eleifend ipsum. Aliquam fermentum, nisi at cursus tempor, augue tortor imperdiet velit, vitae pretium sem diam in risus. Aenean fermentum dolor dui, ac ullamcorper massa rhoncus eu. Donec finibus lorem ligula, ac egestas lectus faucibus non. Suspendisse luctus felis felis, a sollicitudin turpis scelerisque eget. Nunc lacinia sollicitudin semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris nec feugiat leo. Sed sit amet odio ultricies massa egestas lacinia porttitor quis nisl. Phasellus cursus vulputate massa, vel aliquam odio lobortis et. Ut imperdiet leo id tincidunt varius. Curabitur a euismod felis. Nunc a leo quis enim feugiat vulputate. Morbi ligula ligula, vehicula id massa sit amet, imperdiet ullamcorper enim. Duis odio tellus, laoreet at pharetra vel, lacinia id erat. Donec nec risus sit amet libero bibendum posuere sed vitae arcu. Ut luctus sem at eleifend tincidunt. Sed hendrerit blandit dignissim. Duis vel sodales nisi. Nullam a suscipit dui. Nam a purus faucibus, semper odio in, sollicitudin tortor.</p>
  </div>
)
